services:
  bballdaniel3:
    build: .
    ports:
      - "1234:1234"
    environment:
      - NODE_ENV=production
    volumes:
      - ./app/data:/app/data
    command: ["npx", "nodemon", "--legacy-watch", "--ignore", "app/data/*", "server.js"]
    restart: unless-stopped
