const writingPrompts = [
    "Write about a time you overcame a challenge.",
    "Describe your favorite place in detail.",
    "What is your biggest dream and how do you plan to achieve it?",
    "Write a letter to your future self.",
    "If you could have dinner with any historical figure, who would it be and why?",
    "You are a Police Officer in Miami in the 1980's on a drug bust. You have just completed the drug transaction.",
    "You are a commercial airline pilot cruising at 30,000 feet. You’ve just noticed someone is sitting on the wing.",
    "You are a ride operator working the night shift. You’ve just watched one of the animatronics step off its track.",
    "Every clock in town stops at exactly 3:17 a.m., except the one in your bedroom.",
    "A package arrives with your name on it, postmarked fifty years from now.",
    "The new neighbor only leaves their house when it rains.",
    "You wake up able to understand animals, and your dog has an urgent warning.",
    "A hidden door appears in the school library after the final bell.",
    "The last person on Earth hears a knock at the door.",
    "Your reflection waves at you after you have already turned away.",
    "A thief steals a painting and discovers the people inside it are alive.",
    "Everyone in the city receives the same anonymous text: Run.",
    "An astronaut returns from Mars with one extra crew member.",
    "A child finds a dragon egg in a carton from the grocery store.",
    "You inherit a lighthouse whose beam reveals things that are normally invisible.",
    "The village monster arrives each year, but this time it asks for help.",
    "A wizard loses their magic on the morning of the kingdom's most important battle.",
    "The royal chef discovers that one recipe can change the eater's memories.",
    "A knight is sent to rescue a princess who does not want to be rescued.",
    "Every lie you tell becomes true for exactly one hour.",
    "A map tattoo appears on your arm and changes whenever you make a decision.",
    "The moon disappears, and only one small town seems to remember it existed.",
    "A time traveler keeps appearing in the background of your family photos.",
    "You buy an old camera that photographs events one day before they happen.",
    "A robot designed to clean houses decides it wants to become a detective.",
    "The first colony on another planet discovers ruins beneath its landing site.",
    "A spaceship receives a distress signal sent from its own future.",
    "In a world where dreams are recorded, someone edits yours overnight.",
    "Your phone begins receiving voicemails from an alternate version of you.",
    "A scientist invents teleportation, but something always comes back changed.",
    "The city's artificial intelligence asks one citizen to help it escape.",
    "A museum guard notices a different exhibit vanishes every midnight.",
    "The detective realizes every suspect has the exact same alibi.",
    "A famous magician disappears during a trick and leaves behind a coded message.",
    "You find a key in your pocket but have no idea what it opens.",
    "A stranger at the train station hands you a suitcase and vanishes.",
    "The footprints in the snow begin at your front door and end in the middle of a frozen lake.",
    "A sleepy town wakes to find every road leading out has disappeared.",
    "The witness to a crime can only communicate through song lyrics.",
    "A journal in an abandoned cabin describes everything you did yesterday.",
    "During a blackout, a single apartment window remains brightly lit.",
    "Two rival treasure hunters discover they each have half of the same map.",
    "A pirate captain learns the legendary buried treasure is not gold at all.",
    "Your hiking trail changes behind you, making it impossible to turn back.",
    "An explorer finds a city that appears on no map and whose residents know their name.",
    "A submarine crew hears music coming from the deepest part of the ocean.",
    "A routine train ride suddenly continues beyond the end of the tracks.",
    "You enter a race in which the route crosses three impossible worlds.",
    "A storm strands an unlikely group together in a roadside diner.",
    "The elevator opens onto a floor that does not exist.",
    "A hot-air balloon lands in a country no one aboard has ever heard of.",
    "Your first day at a new job includes instructions for surviving a monster attack.",
    "A wedding is interrupted by someone claiming to be the couple's child from the future.",
    "The world's worst superhero accidentally saves the city.",
    "A ghost tries to haunt a house but is terrified of its new residents.",
    "You discover your cat has been secretly running a successful business.",
    "An alien invasion is delayed because the invaders cannot find parking.",
    "A genie grants wishes with surprisingly mundane side effects.",
    "Two villains discover they have both chosen the same hero as their nemesis.",
    "A medieval knight is transported into a modern-day supermarket.",
    "The school talent show becomes unexpectedly important to saving the world.",
    "A fortune cookie gives increasingly specific and inconvenient instructions.",
    "Everyone gains a superpower on their eighteenth birthday; yours seems completely useless.",
    "You are hired to deliver a birthday cake to the top of a haunted mountain.",
    "A shy librarian must return an overdue book to the ruler of the underworld.",
    "The family reunion includes one guest whom nobody invited but everyone recognizes.",
    "A small-town baker discovers their bread makes people tell the truth.",
    "Your imaginary childhood friend returns and has not aged a day.",
    "A musician plays a forgotten melody that summons a mysterious audience.",
    "Two strangers switch bodies whenever they sneeze.",
    "A taxi driver picks up a passenger who requests a destination in the past.",
    "The new student seems to know everyone's secrets before introductions begin.",
    "A handwritten note inside a library book changes each time it is opened.",
    "You receive an invitation to a party at your childhood home, which was demolished years ago.",
    "An old friendship is tested when both friends discover the same extraordinary secret.",
    "A town holds a festival to celebrate an event no visitor can remember happening.",
    "Someone leaves a bouquet at your door every morning with one flower missing.",
    "A character discovers their happiest memory belongs to someone else.",
    "The only person who believes your impossible story is your greatest rival.",
    "A forgotten voicemail changes the course of a family road trip.",
    "A storm washes a message in a bottle onto your doorstep, hundreds of miles from the sea.",
    "You meet an elderly stranger who knows exactly what you wished for as a child.",
    "The kingdom's annual prophecy contains a spelling mistake with dangerous consequences.",
    "A gardener plants mysterious seeds that grow into miniature houses.",
    "The river begins flowing backward, carrying long-lost objects into town.",
    "At sunset, every shadow detaches from its owner and walks toward the forest.",
    "A young inventor builds a machine that can translate the language of stars.",
    "The ocean retreats overnight, revealing a road stretching beyond the horizon.",
    "A cursed crown chooses the least ambitious person in the kingdom as its ruler.",
    "A monster hunter discovers the creature they seek has been protecting the village.",
    "The seasons begin changing every twenty-four hours.",
    "A traveling carnival offers one game whose prize is a second chance.",
    "A spell causes everyone in the castle to forget who the monarch is.",
    "You wake aboard a ship where every passenger claims to be the captain.",
    "A secret society meets beneath a laundromat to guard an ordinary-looking sock.",
    "The town statue climbs down from its pedestal and asks for directions.",
    "A meteor lands in your backyard and begins humming your favorite song.",
    "The final page of every book in the world suddenly becomes blank.",
    "A door-to-door salesperson offers you bottled luck with a warning label.",
    "You find a tiny civilization living inside the walls of your apartment.",
    "A radio broadcasts tomorrow's news, including a story about you.",
    "The annual neighborhood scavenger hunt leads to a genuine hidden treasure.",
    "A snow globe on the mantel perfectly copies the weather outside, then shows an approaching storm."
];

/**
 * Return a random prompt from the story game's prompt list.
 *
 * The random function is injectable to make the helper deterministic in tests.
 */
function getWritingPrompt(random = Math.random) {
    const promptIndex = Math.floor(random() * writingPrompts.length);
    return writingPrompts[promptIndex];
}

module.exports = { getWritingPrompt, writingPrompts };
