name: Update Copilot Instructions

on:
  push:
    branches: [ main ]
    paths:
      - 'package.json'
      - 'app/**'
      - '.github/workflows/**'
      - 'docker-compose.yml'
      - 'Dockerfile'
  pull_request:
    branches: [ main ]
    paths:
      - 'package.json'
      - 'app/**'
      - '.github/workflows/**'
      - 'docker-compose.yml'
      - 'Dockerfile'

jobs:
  check-instructions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check if copilot instructions need updates
        id: check
        run: |
          echo "Checking if copilot instructions may need updates based on recent changes..."
          
          # Check if package.json changed (dependencies/scripts)
          if git diff --name-only HEAD~1..HEAD | grep -q "package.json"; then
            echo "::notice::package.json was modified - consider updating dependency list in copilot instructions"
            echo "dependencies_changed=true" >> $GITHUB_OUTPUT
          fi
          
          # Check if app structure changed
          if git diff --name-only HEAD~1..HEAD | grep -q "^app/"; then
            echo "::notice::App directory structure may have changed - consider updating project structure in copilot instructions"
            echo "structure_changed=true" >> $GITHUB_OUTPUT
          fi
          
          # Check if workflows changed
          if git diff --name-only HEAD~1..HEAD | grep -q "^.github/workflows/"; then
            echo "::notice::Workflows changed - consider updating development workflow section in copilot instructions"
            echo "workflow_changed=true" >> $GITHUB_OUTPUT
          fi
          
          # Check if docker configuration changed
          if git diff --name-only HEAD~1..HEAD | grep -E "(docker-compose\.yml|Dockerfile)"; then
            echo "::notice::Docker configuration changed - consider updating deployment section in copilot instructions"
            echo "docker_changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Validate copilot instructions format
        run: |
          if [ -f ".github/copilot-instructions.md" ]; then
            echo "Validating copilot instructions format..."
            
            # Check for required sections
            if ! grep -q "## Project Overview" .github/copilot-instructions.md; then
              echo "::error::Missing 'Project Overview' section in copilot instructions"
              exit 1
            fi
            
            if ! grep -q "## Technology Stack" .github/copilot-instructions.md; then
              echo "::error::Missing 'Technology Stack' section in copilot instructions"
              exit 1
            fi
            
            if ! grep -q "## Coding Standards" .github/copilot-instructions.md; then
              echo "::error::Missing 'Coding Standards' section in copilot instructions"
              exit 1
            fi
            
            echo "Copilot instructions format validation passed"
          else
            echo "::error::Copilot instructions file not found at .github/copilot-instructions.md"
            exit 1
          fi

      - name: Comment on PR if updates needed
        if: github.event_name == 'pull_request' && (steps.check.outputs.dependencies_changed == 'true' || steps.check.outputs.structure_changed == 'true' || steps.check.outputs.workflow_changed == 'true' || steps.check.outputs.docker_changed == 'true')
        uses: actions/github-script@v7
        with:
          script: |
            const output = `## Copilot Instructions Update Reminder
            
            This PR includes changes that may require updates to the Copilot instructions:
            
            ${process.env.DEPENDENCIES_CHANGED === 'true' ? '- Dependencies changed - consider updating the dependency list\n' : ''}${process.env.STRUCTURE_CHANGED === 'true' ? '- App structure changed - consider updating the project structure section\n' : ''}${process.env.WORKFLOW_CHANGED === 'true' ? '- Workflows changed - consider updating the development workflow section\n' : ''}${process.env.DOCKER_CHANGED === 'true' ? '- Docker configuration changed - consider updating the deployment section\n' : ''}
            
            Please review and update [\`.github/copilot-instructions.md\`](.github/copilot-instructions.md) if necessary.`;
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            });
        env:
          DEPENDENCIES_CHANGED: ${{ steps.check.outputs.dependencies_changed }}
          STRUCTURE_CHANGED: ${{ steps.check.outputs.structure_changed }}
          WORKFLOW_CHANGED: ${{ steps.check.outputs.workflow_changed }}
          DOCKER_CHANGED: ${{ steps.check.outputs.docker_changed }}
